<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
#We can only multiply matrices if the number of columns in the first matrix is the same as the number of rows in the second matrix
def matrix_mul(A, B):
  try:
      if len(A[0]) == len(B):
        for i in range(len(A[0])):
          if len(A[i]) == len(A[i+1]) and len(B[i]) == len(B[i+1]):           # Checking the size of all columns in both matrices.
                    return [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]  # List comprehension which returns the matrix multiplication. 
          else:
            print("All columns must have same number of elements")
      else:
          print("Matrix multiplication is not possible")
  except:
    print("Please enter correct format of the matrix /check elements in rows and columns or Size of the matrix. ")

In [0]:
## Example 1: 

A   = [[1,3,4],
       [2,5,7],
       [5,9,6]]
B   = [[1,0,0],
       [0,1,0],
       [0,0,1]]
# A*B = [[1 3 4][2 5 7][5 9 6]]

matrix_mul(A,B)


[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [0]:
## Example  2: 
A   = [[1,2],[3,4]]
B   = [[1,2,3,4,5],[5,6,7,8,9]]
## A*B = [[11 14 17 20 23] [18 24 30 36 42]]
matrix_mul(A,B)


[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

In [0]:
## Example 3: 
A   = [[1,2],[3,4]]
B   = [[1,4],[5,6],[7,8],[9,6]]

##A*B =Not possible
matrix_mul(A,B)

Matrix multiplication is not possible


In [0]:
## Example 4
A   = [[1,2],[3,4]]
B   = [[1,4],['s',6]]

## Some error it should throw as B[1][0] is alphabet
matrix_mul(A,B)


Please enter correct format of the matrix /check elements in rows and columns or Size of the matrix. 


In [0]:
### Example 5
A   = [[1,2],[3,4]]
B   = [[1,4],[6]]

## Some error it should throw as B[1][0] or B[1][1] is null/empty
matrix_mul(A,B)

All columns must have same number of elements
Please enter correct format of the matrix /check elements in rows and columns or Size of the matrix. 


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [0]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

## Source :: https://stackoverflow.com/questions/57892112/select-a-number-randomly-with-probability-proportional-to-its-magnitude-from-the

# you can free to change all these codes/structure
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

## Source :: https://stackoverflow.com/questions/57892112/select-a-number-randomly-with-probability-proportional-to-its-magnitude-from-the

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    Sum = 0
    for i in range(len(A)):
        Sum+=A[i]                    ## Sum of all elements in the list    
    A_dash = []                    
    for i in range(len(A)):         
        b=A[i]/Sum                    ## Dividing each element in the list by sum of list 
        A_dash.append(b)              ## Adding the new real number to A_dash list
    cumsum=[]
    cumsum.append(A_dash[0])          ## Creating and adding 0th element of Cummulative Sum list { if we don't append oth element it throws an error in next { index out of range}}
    for j in range(1, len(A)):
      cumsum.append(cumsum[j-1]+A_dash[j])    ## adding the cumsum 0th element and A_dash 1st element, adding gives cummulative sum. 

    sample_value = uniform(0.0,1.0)            ## Creating the sample value from unifrom in between 0 and 1.  
    r = sample_value
    print(r)          
    if r<cumsum[1]:                                ## Comparing the cumsum elements with sample values and returning the magnitude value.
            return 1
    elif r>cumsum[1] and r <cumsum[2]:  
            return 2
    elif r<cumsum[3]: 
            return 3
    elif r<cumsum[4]: 
            return 4
    elif r<cumsum[5]: 
            return 5
    elif r<cumsum[6]:  
            return 6
    elif r<cumsum[7]: 
            return 7
    elif r<cumsum[8]: 
            return 8
    elif r<cumsum[9]:
            return 9


def sampling_based_on_magnitued():

    A = [0,5,27,6,13,28,100,45,10,79]
    for i in range(1,10):
      num = pick_a_number_from_list(A)
    print(A[num])

sampling_based_on_magnitued()

0.05101930467537008
0.5966356410152207
0.546850080360059
0.2463777731730783
0.28620724495833927
0.9947689965480401
0.40682627990027687
0.5026221743717986
0.49348399717853286
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String): 
  if type(String) == int:                              ## Cheking whether the user input is string or int.
    print("Please enter string")
  else:
    for char in String:                                 ## Iterating through all characters in the entered string.
      Ash = ''.join('#' for char in String if char.isdigit())      ## Replacing the digits with "#" and ingoring remaining 
    return Ash                                          ## Returning the Ash

In [0]:
## Example 1: 
A = '234'                
# Output: ###
replace_digits(A)

'###'

In [0]:
## Example 2:
A = 'a2b3c4'             
# Output: ###
replace_digits(A)

'###'

In [0]:
## Example 3:
A = 'abc'                
# Output:   (empty string)
replace_digits(A)

''

In [0]:
## Example 4:
A = '#2a$#b%c%561#'      
# Output: ####
replace_digits(A)

'####'

In [0]:
## Example 5:
A = 345      
# Output: ####
replace_digits(A)

Please enter string


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

## We can make use of Zip funciton , which combines two lists based on Index. 
def display_dash_board(Students, Marks):
    #zip the two lists, create a new sorted list based on zip 
    if((len(Students)!=0 and len(Marks)!=0) and len(Students) == len(Marks)):
        #Zipping and converting into list bases on Index values lile [('student1', 45), ('student2', 78)............]
        zipped = list(zip(Students,Marks))
        ## Sorting the Zipped values in ascending order
        Sorted_Students = list(sorted(zipped,key=lambda x :x[1],reverse=True))
        print("Top 5 students are")
        for i in range(0,5):                      
          print(Sorted_Students[i][0],":",Sorted_Students[i][1])
        print("\nLeast 5 students are")
        for i in range(-5,0,1):
          print(Sorted_Students[i][0],":",Sorted_Students[i][1])
        print("\nStudents_within_25_and_75")
        Marks = sorted(Marks)
        Min_Marks = Marks[0]
        Max_Marks = Marks[-1]
        Min_Max = Max_Marks - Min_Marks
        percentile_25 = Min_Max*0.25
        percentile_75 = Min_Max*0.75
        for i in range(len(Marks)):
          if  percentile_25 <  Sorted_Students[i][1] < percentile_75:
            print(Sorted_Students[i][0],":",Sorted_Students[i][1])  
    else:
      print("Please enter Lists of same size or non empty strings")

In [0]:
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35,80]
display_dash_board(Students, Marks)

Top 5 students are
student8 : 98
student10 : 80
student2 : 78
student5 : 48
student1 : 45

Least 5 students are
student7 : 45
student6 : 43
student9 : 35
student4 : 14
student3 : 12

Students_within_25_and_75
student5 : 48
student1 : 45
student7 : 45
student6 : 43
student9 : 35


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [0]:
import math
P = (3, -4) 
S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
cosine_dist = []

for x,y in S:

    xintoy_plus_yintoq = x * P[0] + y * P[1]
    sqrt_of_xypq = math.sqrt(x * x + y * y) * math.sqrt(P[0] * P[0] + P[1] * P[1])
    cosine_dist.append(math.acos(xintoy_plus_yintoq/sqrt_of_xypq))
## List of acos values like [2.0344439357957027, 1.8545904360032246......]
X = cosine_dist                  
## Sorted List od tuples with point and acosine values like [((6, -7), 0.06512516333438509), ((1, -1), 0.14189705460416438).....]
Y = [S for S in sorted(zip(S,X), key=lambda i:i[1])] 
## accessing the first 5 points from list of tuples
k = Y[:5]   
# Printing the points which are near to list
for i, j in k:
    print(i)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


I am getting an error while executing the with fucntion saying 
'tuple' object is not callable
So, Wrote code without function.


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

Let there be a point (x1,y1) and a line ax1+by1+c=0 on a Cartesian plane. Just put the values of point in the given equation and evaluate..

If ax1+by1+c>0 then the point is above the line.

If ax1+by1+c<0 then the point is below the line.

If ax1+by1+c=0 then the point is on the line.

In [0]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in range(len(Lines)):
  red_Points = []
  blue_Points = []
  Coordinates=(' '.join(' '.join(Lines[i].split('x')).split('y'))).split(' ')   ## getting coordinCoordinatestes 
  for j in range(len(Red)):
     ## Computing the distance by replacing the x and y values from Red points  / coordinates 
    pointR = Red[j][0]*float(Coordinates[0])+Red[j][1]*float(Coordinates[1])+float(Coordinates[2])  
    red_Points.append(pointR)            # Appending the distance to list red_Points
  for k in range(len(Blue)): 
     ## Computing the distance by replacing the x and y values from blue points / coordinates             
    pointB = Blue[k][0]*float(Coordinates[0])+Blue[k][1]*float(Coordinates[1])+float(Coordinates[2])
    blue_Points.append(pointB)          # Appending the distance to list red_Points
  
  red_Points_P= red_Points_N=blue_Points_N=blue_Points_P=0
  ## If the distance is greater than zero the coordinates on the one side of plane else the other side of plane. 
  
  for i in range(len(red_Points)):    ## Iterating for all distance for redpoints. 
    if red_Points[i]>0:               ## Checking , if the distance is more than zero 
      red_Points_P+=1                 ## if more than zero adding to positive list 
    else:
      red_Points_N+=1                 ## If less than zero adding to negative list
  if red_Points_P==len(red_Points):      ## Calcualting same for blue points as well 
    for i in range(len(blue_Points)):
      if blue_Points[i]<0:
        blue_Points_N+=1
    if blue_Points_N==len(blue_Points):      ## Here if all points lies in one side of plane , the count is equal to lenght of list.
      print ('YES')                          ## if count is equal to lenght , it returns YES
  elif red_Points_N==len(red_Points):
    for i in range(len(blue_Points)):         ## Same calculates for Blue points as well. 
      if blue_Points[i]>0:
        blue_Points_P+=1
    if blue_Points_P==len(blue_Points):  
      print ('YES')
  else:
    print ('NO')

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    _Count=0                                  ## To Calculate "#" count in between two given numbers
    numCount = 0                              ## To add up the digits in given string.
    stringList = string.split(",")            ## Spliting the given string based on comma(,) and storing the resultin form of list
    for i in stringList:                      ## Running lopp for all characters in stringList list.
        if i=="_":                            ## if any of the element is '#' it goes within loop and counts.
            _Count+=1
        else:                      
            numCount=int(i)+numCount          ## If the element is digit, as it is string , converting it to int and adding to numCount. { 0 + 30 = 30}
    
    replaceSequence = int(numCount/len(stringList))      ## Calcualting the equal distributed numbers between numbers { 30+50/(len(string) =8) = 80/8 = 10 }
    replaceNumber=[]                                    ## Creating an empty list
    for i in range(len(stringList)):                    
        replaceNumber.append(str(replaceSequence))         ## Here , for every iteration from 0 to len(string), number 10 is added to empty list
    return ','.join(replaceNumber)                      ## Finally returning the new list with replaced values

In [0]:
S=  "_,_,_,24"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

6,6,6,6


In [0]:
S=  "80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

16,16,16,16,16


In [0]:
S=  "40,_,_,_,60"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

20,20,20,20,20


I wrote the code for above with bounbdary cases but i faced many challences and finally came with below code for the String = "_,_,30,_,_,_,50,_,_"

Source :: https://stackoverflow.com/questions/57179618/filling-the-missing-values-in-the-specified-format-python

Only below copied from stackoverflow but I understood it before. 

In [0]:
def curve_smoothing(string):
    lst=string.split(',')                         ## Splitting the list based on comma(,)
    for i in range(len(lst)):           
        if lst[i].isdigit():                      ## Running the lopp and chekcing it is digit or not.
                lst[j]=int(lst[i])//(i+1)         ## Running floor division(2) for the to get an int and stores in list
            new_index=i                           ## Storing the index where it finds the number from string.
            new_value=int(lst[i])                 ## Storing the number from the index where it finds the number from string.
            break                               
    for i in range(new_index+1,len(lst)):           ## Again running lopp form next element from string ( index where it found to last)
        if lst[i].isdigit():                        ## Repeats the same till it finds the next digit instead of "#"
            temp=(new_value+int(lst[i]))//(i-new_index+1)
            for j in range(new_index,i+1):
                lst[j]=temp
            new_index=i
            new_value=int(lst[i])
    try:
        for i in range(new_index+1,len(lst)):            ## it calculates the number equally distributed between the two numbers and repalce them at index. 
            if not(lst[i].isdigit()):
                count=lst.count('_')
                break
        temp1=new_value//(count+1)
        for i in range(new_index,len(lst)):
            lst[i]=temp1
    except:
        pass
    return lst 

In [0]:
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


But i am unable ot combine both on boundary conditions. If you accept the above code i am fine. if not kindly suggest me . Thanks !! 

I have an idea to store the first digit to second digit in a new list and replace with Sum/len(of list between to digits ) and next calculate from second digit to third digit and replace it with sequence ........I tried in many ways but failed due to boundary conditions. 

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




I tried on my own but failed at many failed cases. So, copied from below source before that I understood the code. 

Modified the code a bit from Source.

Source : https://stackoverflow.com/questions/57160252/find-conditional-probabilities-using-python

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

listCombine = []
listDen = []
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]
def compute_conditional_probabilites(A):
  for i in range(len(A)):
    k = A[i][0]+A[i][1]
    listDen.append(A[i][1])
    listCombine.append(k)

compute_conditional_probabilites(A)
print("a.")
print("conditional probability P(F=F1|S==S1)=1/4-----",(listCombine.count('F1S1')/listDen.count('S1')))
print("conditional probability P(F=F1|S==S2)=1/3-----",(listCombine.count('F1S2')/listDen.count('S2')))
print("conditional probability P(F=F1|S==S3)=0/3-----",(listCombine.count('F1S3')/listDen.count('S3')),"\n")
print("b.")
print("conditional probability P(F=F2|S==S1)=1/4-----",(listCombine.count('F2S1')/listDen.count('S1')))
print("conditional probability P(F=F2|S==S2)=1/3-----",(listCombine.count('F2S2')/listDen.count('S2')))
print("conditional probability P(F=F2|S==S3)=1/3-----",(listCombine.count('F3S3')/listDen.count('S3')),"\n")
print("c.")
print("conditional probability P(F=F3|S==S1)=0/4-----",(listCombine.count('F3S1')/listDen.count('S1')))
print("conditional probability P(F=F3|S==S2)=1/3-----",(listCombine.count('F3S2')/listDen.count('S2')))
print("conditional probability P(F=F3|S==S3)=1/3-----",(listCombine.count('F3S3')/listDen.count('S3')),"\n")
print("d.")
print("conditional probability P(F=F4|S==S1)=1/4-----",(listCombine.count('F4S1')/listDen.count('S1')))
print("conditional probability P(F=F4|S==S2)=0/3-----",(listCombine.count('F4S2')/listDen.count('S2')))
print("conditional probability P(F=F4|S==S3)=1/3-----",(listCombine.count('F4S3')/listDen.count('S3')),"\n")
print("e.")
print("conditional probability P(F=F5|S==S1)=1/4-----",(listCombine.count('F5S1')/listDen.count('S1')))
print("conditional probability P(F=F5|S==S2)=0/3-----",(listCombine.count('F5S2')/listDen.count('S2')))
print("conditional probability P(F=F5|S==S3)=0/3-----",(listCombine.count('F5S3')/listDen.count('S3')))

a.
conditional probability P(F=F1|S==S1)=1/4----- 0.25
conditional probability P(F=F1|S==S2)=1/3----- 0.3333333333333333
conditional probability P(F=F1|S==S3)=0/3----- 0.0 

b.
conditional probability P(F=F2|S==S1)=1/4----- 0.25
conditional probability P(F=F2|S==S2)=1/3----- 0.3333333333333333
conditional probability P(F=F2|S==S3)=1/3----- 0.3333333333333333 

c.
conditional probability P(F=F3|S==S1)=0/4----- 0.0
conditional probability P(F=F3|S==S2)=1/3----- 0.3333333333333333
conditional probability P(F=F3|S==S3)=1/3----- 0.3333333333333333 

d.
conditional probability P(F=F4|S==S1)=1/4----- 0.25
conditional probability P(F=F4|S==S2)=0/3----- 0.0
conditional probability P(F=F4|S==S3)=1/3----- 0.3333333333333333 

e.
conditional probability P(F=F5|S==S1)=1/4----- 0.25
conditional probability P(F=F5|S==S2)=0/3----- 0.0
conditional probability P(F=F5|S==S3)=0/3----- 0.0


Here We can convert the list into dict with default value zero for all keys for any given length of list.

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
  Words_in_S1 = set(S1.split())                                ## Spliting and convrerting into set for sentence 1
  Words_in_S2 = set(S2.split())                                ## Spliting and convrerting into set for sentence 2
  a = list(Words_in_S1.intersection(Words_in_S2))              ## Common words is nothing but intersection. so returning the common words in form of list.
  a_count = len(a)                                             ## Calculating the len of list which returns number of commons words       
  b = list(Words_in_S1.difference(Words_in_S2))                ## Difference is nothing but which ignores common words and return only unique from S1 for this line
  c = list(Words_in_S2.difference(Words_in_S1))                ## Difference is nothing but which ignores common words and return only unique from S2 for this line
  return a_count, b, c                                         ## Returning the count , unique words in S1 and S2.

In [0]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(" a :",a,"\n","b :",b,"\n","c :",c)

 a : 7 
 b : ['F', '5', 'first'] 
 c : ['S', '3', 'second']


In [0]:
S1= "Applied AI Course is best of all Analysis courses in India."
S2= "AAIC is desinged as per industry standards in India and it has good placement options."
a,b,c = string_features(S1, S2)
print(" a :",a,"\n","b :",b,"\n","c :",c)

 a : 2 
 b : ['AI', 'of', 'best', 'Course', 'Applied', 'India.', 'Analysis', 'all', 'courses'] 
 c : ['India', 'desinged', 'as', 'has', 'placement', 'options.', 'per', 'and', 'industry', 'AAIC', 'standards', 'good', 'it']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math

def compute_log_loss(A):
  compute_loss = 0  
  try:
    for i in range(len(A)):                      ## Running loop for all points in the list of lists.
       compute_loss += (A[i][0] * (math.log10(A[i][1]))) + ((1 - A[i][0]) * (math.log10(1 - A[i][1])))   ## Computing loss for all points.
       loss = -1*(1/len(A))*compute_loss     ##  Calculating loss by dividing the compute_loss by len of list of list.
    return loss                                ## Returning the loss values
  except:
    print("Please enter digits.")
  
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
